### ISSUE TITLE
It is recommended that a robustness level be specified.

### ISSUE THREAD

**Issue by HackerBoy0412** [openstrikesback/widevine-l3-decryptor#1]
On Edge comes the message ,,It is recommended that a robustness level be specified. Not specifying the robustness level could result in unexpected behavior,, and to keys shows up.
![Unbenannt](https://user-images.githubusercontent.com/27073934/99457191-ddb62880-292a-11eb-8492-bdf65da27b4a.PNG)

**Comment by Doregon** [comment]
I'm looking into how the extension "talks" to Chrome and Widevine.

**Comment by Doregon** [comment]
Does this happen when you load the unpacked version?

**Comment by Doregon** [comment]
Okay, after looking into how the extension communicates with the browser, it's just a warning that **we can disregard.** We don't need to specify how the encoder should work with our extension.

**Comment by Doregon** [comment]
I will be adding documentation regarding this issue once I work on compatibility with other operating systems.
